#!/bin/zsh

# A wrapper to interface Indigo to tplink-smartplug.py
# Can be used to create a virtual machine

# Location of tplink_smartplug.py
TPLINK=/usr/local/bin/tplink_smartplug.py
# IP Address on the smart plug
PLUGADDR=192.168.5.113

#### Do not change anything below this line ####
FUNC=$1

# get the pid of the Indigo TPLink monitor so we can tell it when to update
PID=`pgrep -f tpmonitor.py|head -1`
alias tpOn='$TPLINK -t $PLUGADDR -c on >/dev/null 2>&1'
alias tpOff='$TPLINK -t $PLUGADDR -c off >/dev/null 2>&1'
alias tpStatus='kill -SIGUSR1 $PID;$TPLINK -t $PLUGADDR -c info | grep Received | sed -e "s/Received..//" | json_pp | grep relay_state | cut -c26 | tr -d "\n"'

case $FUNC in
	on)
		tpOn
		tpStatus
		;;
	off)
		tpOff
		tpStatus
		;;
	toggle)
		STATE=`tpStatus`
		case $STATE in
			0) 
				tpOn
				tpStatus
				;;
			1)
				tpOff
				tpStatus
				;;
			*)
				echo Unknown state $STATE received from plug
       			 	exit 1
				;;
		esac
		;;
	status)
		tpStatus
		;;
	*)
        	echo Error: on, off or status required
        	exit 1
		;;
esac

exit 0

